export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const EMPTY_CART="EMPTY_CART"
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const SELECT_HEADER_ITEM='SELECT_HEADER_ITEM';

